version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./project:/var/jenkins_home/workspace/ts-jest
    user: root
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "test"]

volumes:
  jenkins_home:
  